### ISSUE TITLE
Request from BNPB

### ISSUE THREAD

**Issue by fadmastuti** [urbanriskmap/cognicity-reports-twitter#5]
@matthewberryman , we have requested by BNPB to show our flood report statistics since PetaJakarta was launched in 2014. there are:

1. how many people have reported flood through twitter (confirmed and unconfirmed)
2. how many people have used #flood or #banjir on twitter
3. how many people hit our PetaJakarta web?

thank you

**Comment by matthewberryman** [comment]
This isn't related to the code so I'll close it and get back to you on email.
